p1
Michalski84/nodejs-hw-02 pull request #1
Opened 2024-04-17 15:23 UTC by Michalski84

Witam

2024-04-17 20:45 UTC, KamilMr requested changes
Hej, 
Potrzebujesz jeszcze zrobić validację joi oraz zobacz plik routes/api/contacts.js. Bo widzę że jego nie używasz do obsługi kontaktów a używasz app.js.

2024-04-17 20:45 UTC, KamilMr commented on models/contacts.json
> +    "name": "Andrzej",
Zobacz że brakuje Ci jeszcze Id :) użyj np `uuid` do tego aby je generować :)

2024-04-17 20:45 UTC, KamilMr commented on models/contacts.json
> +    "name": "Papa Smerf",
:)

2024-04-17 20:45 UTC, KamilMr commented on routes/api/contacts.js
> +const { validateContact, validateUpdate } = require('../../middlewares/validation');
Zauważ że tego nie masz, więc może zapomniałeś dodać?

2024-04-17 20:45 UTC, KamilMr commented on routes/api/contacts.js
Nie rozumiem tego pliku, zobacz że w app.js masz całą logikę, więć jaka jest rola tego pliku? Domyślam się że przez pomyłkę go zrobiłeś. Możesz przenieść punkty końcowe z app.js tutaj albo usunąć ten plik.

2024-04-17 20:45 UTC, KamilMr commented on app.js
> +    return res.status(400).json({ message: 'missing required name, email, or phone field' });
Użyj tutaj validacji z joi

2024-04-17 20:45 UTC, KamilMr commented on app.js
> +    const contact = await addContact({ name, email, phone });
Pamiętaj aby wygenerować id, użyj paczki uuid :)

2024-04-17 20:45 UTC, KamilMr commented on app.js
> +  if (!name || !email || !phone) {
Validacja joi tutaj też jest potrzebna :)

2024-04-20 12:24 UTC, Michalski84 commented
Dzień dobry,

Poprawki naniesione. 
Pozdrawiam :)

2024-04-20 19:01 UTC, merged